default_platform(:ios)

platform :ios do
  desc "Run all tests"
  lane :test do
    scan(
      scheme: "AIVibe",
      devices: ["iPhone 15"],
      force_destroy_simulator: true,
      derived_data_path: "DerivedData"
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    match(
      app_identifier: "ru.aivibe.app",
      type: "appstore",
      readonly: true
    )

    build_app(
      scheme: "AIVibe",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual"
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
